### ISSUE TITLE
how connect vuetify

### ISSUE THREAD

**Issue by frostspb** [team-innovation/vue-sfc-rollup#10]
Hi! I have a question. My component depend from Vuetify, how a can connect it to dev server in entry.js?

**Comment by mgdodge** [comment]
This is really a question about using vue cli dev server, not vue-sfc-rollup. But this seems like a pretty common scenario, so I went through the paces anyway.

The CLI documentation section on [Instant Prototyping](https://cli.vuejs.org/guide/prototyping.html) says you can pass a vue file or a js file as the entry point. So instead of running `vue serve ./src/my-component.vue` on the component itself, you can run `vue serve ./load-dev-dependencies.js` to point to a custom js file which loads vuetify and any other dependencies. That file could be as simple as:

```javascript
import 'material-design-icons-iconfont/dist/material-design-icons.css'; // Ensure you are using css-loader
import 'vuetify/dist/vuetify.min.css'; // Ensure you are using css-loader
import Vue from  'vue';
import Vuetify from 'vuetify';
import MyComponent from './src/entry';

// install vuetify and any other dependencies
Vue.use(Vuetify, {
    iconfont: 'mdi'
});

// Mount custom component in div provided by vue cli dev server
new Vue({ render: h => h(MyComponent) }).$mount('#app');
```

This loads the dependencies for your dev experience only. **When you build/publish your component, the dependencies are external (not bundled with your component)**, so be sure to document the dependency for your users.
