### ISSUE TITLE
Build of dev lost css style 

### ISSUE THREAD

**Issue by tuguldurio** [team-innovation/vue-sfc-rollup#107]
Just like serving the dev sub directory, I built the dev/serve.ts with `vue-cli-service build dev/serve.ts`, and it worked just fine.
However css styling seems to be lost.

**Comment by mgdodge** [comment]
I don't understand what you are trying to do. There is no reason to run any custom build commands like above. The package.json file already has a build command (for example, [this line](https://github.com/team-innovation/vue-sfc-rollup/blob/e10fca2d7b0706da27e64826f315621fd2b98696/templates/single/single-package.json#L23) in single-component mode). That is the build command you should be using and uses all the rollup scaffolding.

The `dev/serve.ts` file is a helper file for use while you are developing your component, nothing more. It is not intended to be built or be part of your final bundle. What you are doing here will use the vue cli, and in turn, webpack, and will not use any of the configuration provided by this utility. It kind of defeats the whole purpose.

Take a look at the README for this repo/npm package again, and you will see that all the commands you need are already created for you. Closing this issue, since it is a misuse of vue-sfc-rollup.
