### ISSUE TITLE
Generated by project components doesn't work with @vue/test-utils.

### ISSUE THREAD

**Issue by bbones** [team-innovation/vue-sfc-rollup#111]
Generated by project components doesn't work with @vue/test-utils. It works fine with development env. But in tests import component statement generates ReferenceError: regeneratorRuntime is not defined in the component.ssr.js file

Example 
component library
https://github.com/bbones/atree.git
demo for it
https://github.com/bbones/atree-demo.git

**Comment by mgdodge** [comment]
Saying that components scaffolded with this utility don't work with @vue/test-utils is inaccurate, I have used the file structure generated here numerous times with unit tests, and things work fine. But it always involves extra configurations, which I will highlight. But vue-sfc-rollup specifically doesn't change how any third transpilers or testing utilities work. It just creates the minimum configuration files and wrapper installation files required by for rollup, leaving the rest up to the user.

That being said, there are a few problems that I see here:

First, vue-sfc-rollup only scaffolds vue-cli compatible files for publishing to npm. Since this project uses the vue-cli behind the scenes for the dev server, it's trivial to add @vue/cli-plugin-unit-jest to test your component. Any unit tests for the component itself belong in the repo for the component, not the application that consumes it. That is pretty much the definition of a unit test - testing the unit, not the application.

Second, if the unit tests in the application are being blocked by the inclusion of your component, and your component has its own passing unit tests, @vue/test-utils makes it easy to mock external components. That is what should be happening in your application, you should be mocking anything that is not coded directly in the application itself.

Lastly, if you are determined to get tests running in your current setup, you will need to either configure babel in your component to include the regenerator runtimes into the library itself (increases package size slightly), or flag it as a dependency and configure jest in your application to include the regenerator runtimes when running unit tests. This can be done several ways, google and stack overflow can help.

I know this may sound like an unhelpful answer, but the problems all lie in either your project/component babel configs or in the way you are choosing to run unit tests - neither of which is the concern of vue-sfc-rollup. As they are outside the scope of vue-sfc-rollup, I am closing this issue.

**Comment by bbones** [comment]
@mgdodge 
The solution with regeneratorRuntime is simple adding 
`import 'regenerator-runtime/runtime'` 
into test file directly or jest.setup.js but a new error occurs 
[Vue warn]: Error in render: "TypeError: _vm._ssrEscape is not a function" what way do you think I can investigate this problem?
