### ISSUE TITLE
External modules are not supported on browser build (unpkg)

### ISSUE THREAD

**Issue by glopezep** [team-innovation/vue-sfc-rollup#15]
browser build (unpkg) says: ModuleName is not defined. import it from unpkg.com

**Comment by mgdodge** [comment]
I doubt this is an issue with vue-sfc-rollup, since all this package does is scaffold configuration files that are ultimately used by rollup - actual coding of the SFCs is up to you. When you introduce dependencies, please refer to [the rollup documentation](https://rollupjs.org/guide/en#warning-treating-module-as-external-dependency) for help configuring external dependencies (if you are loading the unpkg version, this is likely what you will need.) If you are sure the issue has something to do with the way vue-sfc-rollup is packaging things, please come back with more detailed sample code.
