### ISSUE TITLE
Build doesn't work on server side with nuxt

### ISSUE THREAD

**Issue by glopezep** [team-innovation/vue-sfc-rollup#16]
Is there an alternative for that, some example that you show here?

**Comment by mgdodge** [comment]
There is very little information here to understand exactly what you are referring to. Please provide some example code and more details.

Since nuxt is used for server-side rendering of components, you might need to import the .vue file directly, which is published as part of the npm package for this exact reason. Please read this library's corresponding [Vue cookbook recipe](https://vuejs.org/v2/cookbook/packaging-sfc-for-npm.html#SSR-Usage) for details on how to import the .vue SFC directly - that is exactly how this utility is written.
