### ISSUE TITLE
Does this work hot loading CSS changes?

### ISSUE THREAD

**Issue by praveenpuglia** [team-innovation/vue-sfc-rollup#2]
I have not really tried it but I was trying to build something with egoist/poi and bili today to share a component I built via npm but, the CSS part of the SFC wouldn't update upon build while running in watch mode.

Here's more on this - https://twitter.com/_egoistlily/status/978612899785486339

Wondering if this would fix that problem since it also uses rollup.

**Comment by mgdodge** [comment]
I have not used this for hot reloading. I use the vue cli for the actual development, with its hot reloading capabilities. This is really more of a last-step sort of thing, preparing the SFC for distribution. My intent here is to keep this code as simple as possible, and strictly for packaging.

My personal use case for this actually uses scoped CSS, which is inlined into the js files instead of separated out. I can, however, see a use for extracting the CSS into a separate file. I will look into it, but if you manage to figure it out first, feel free to submit a PR!

**Comment by mgdodge** [comment]
@praveenpuglia is this still an issue/request? rollup and all related plugins have been updated numerous times since this issue was created. Just released v2.0.0 of this utility today, cleaning house a bit, thought I'd reach out. I'll probably end up closing this issue since the vue cli is the officially recommended way of getting a hot-reloading dev experience.

**Comment by praveenpuglia** [comment]
I agree. 
Glad that you reached out after so long. Thanks so much :)
