### ISSUE TITLE
Issues using vue-class-component

### ISSUE THREAD

**Issue by GregOSP** [team-innovation/vue-sfc-rollup#20]
My component runs fine with vue-cli but when I attempt to build I get the following error: `(commonjs plugin) SyntaxError: Unexpected character '@' (101:0)`
The code at line 101 is 
` @Component({`

Am I missing something in the rollup.config file? I set the following external dependencies: 
```
const external = [
  // list external dependencies, exactly the way it is written in the import statement.
  // eg. 'jquery'
  'vue-class-component',
  'fuse.js',
  'lodash',
  'vue-property-decorator'
];
```

**Comment by mgdodge** [comment]
Behind the scenes, the vue cli uses webpack and babel. The setup vue-sfc-rollup generates uses bublé for transpiling instead of babel. This is relevant because vue-class-component uses experimental decorators, which are not yet part of the official spec.

I suspect that you need to swap rollup-plugin-buble for rollup-plugin-babel and make the necessary configuration adjustments.

 For a list of features supported by bublé, refer to [their docs](https://buble.surge.sh/guide/#supported-features).

**Comment by jarekcieslak** [comment]
@GregOSP did you add typescript plugin?

my rollup config looks somewhat like this:
```
import typescript from "rollup-plugin-typescript2";

const baseConfig = {
  input: 'src/entry.js',
  plugins: [
    replace({
      'process.env.NODE_ENV': JSON.stringify('production'),
    }),
    commonjs(),
    typescript({
      useTsconfigDeclarationDir: true,
      clean: true,
      objectHashIgnoreUnknownHack: true,
    }),
    vue({
      css: true,
      compileTemplate: true,
      template: {
        isProduction: true,
      },
    }),
    buble(),
  ],
};
```

and my tsconfig.json file contains:
"experimentalDecorators": true

**Comment by mgdodge** [comment]
If what @jarekcieslak said works, great! I personally don't have as much experience using the vue/typescript decorators. I guess it makes sense if typescript does the first pass that it could add in the appropriate parts.

**Comment by GregOSP** [comment]
@jarekcieslak thanks for the suggestion. Unfortunately I can't get typescript to recognize props defined in `@Component()` as  valid and keep getting an error on compile `semantic error TS2339 Property 'PropName' does not exist on type 'MyComponent'.`
