### ISSUE TITLE
How to implement PostCSS transpiler?

### ISSUE THREAD

**Issue by patrioticcow** [team-innovation/vue-sfc-rollup#22]
Hi,

Looks like PostCSS variables are not being transpiled to just css.
Also maybe throw in there an autoprefixer.

Any ideas how can I integrate this step into this project?
Thank you.

Here's how I do it in NUXT build process.

```
  postcss: {
      plugins: {
        cssnano: {},
        'postcss-import': {},
      },
      preset: {
        stage: 2,
        importFrom: ['src/assets/css/theme.css'],
        features: {
          'nesting-rules': true,
          'custom-media-queries': true,
          'color-mod-function': true,
        },
      },
    },
```

**Comment by mgdodge** [comment]
Unfortunately, I have not used PostCSS as of yet, so I don't have a ready answer. Since vue-sfc-rollup as a tool exists to scaffold the minimum starting point and everything after that is handled by rollup and its plugins, you will likely find better/more information in their repos/forums. Not opposed to contributions if you find a simple solution that doesn't expand the scope of this utility beyond scaffolding a basic configuration.

**Comment by patrioticcow** [comment]
I found a way by creating `postcss.config.js`
Ill see if I get some time to to a pr with an example


```
module.exports = {
  plugins: {
    'postcss-import': {},
    'postcss-preset-env': {
      stage: 3,
      importFrom: ['src/assets/css/theme.css'],
      features: {
        'nesting-rules': true,
        'custom-media-queries': true,
        'color-mod-function': true,
      },
    },
  },
};

```

**Comment by mgdodge** [comment]
Closing this issue. The configurations generated by vue-sfc-rollup are intentionally generic, so as to leave decisions about third party libraries up to the developer.
