### ISSUE TITLE
[Feature Request] Add support for vue-custom-element

### ISSUE THREAD

**Issue by BennyAlex** [team-innovation/vue-sfc-rollup#28]
Hello,

thanks for the cli :)

It would be nice to have direct support for https://github.com/karol-f/vue-custom-element,
which would save some extra configuration for SFC's which are vue independet.

Let me knwo waht you think about this.

Have a ncie day!

**Comment by mgdodge** [comment]
I believe this is beyond the scope of this utility. I don't have information on how many people use vue-custom-element, but this utility aims to generate the minimal config necessary to scaffold a vue SFC for development and publishing to npm. As such, I don't believe this feature makes sense to add. If you feel that you can make a case otherwise, I am happy to consider a pull request.
