### ISSUE TITLE
Can be used to bundle Vue plugins?

### ISSUE THREAD

**Issue by ShailenNaidoo** [team-innovation/vue-sfc-rollup#38]
Hi there :wave: 

I wondering if this CLI tool could be used to bundle Vue plugins, instead of Vue SFCs as well?

Thanks :)

**Comment by mgdodge** [comment]
Yes, it can. Rollup does the actual bundling, this just puts a scaffold in place, but once in place, it can easily be tweaked to do what you need.

Instead of `src/entry.js` you will see it just imports the component(s) that are being packaged, and provides an autoinstall wrapper. This is the file that is used to generate the main for npm. To create plugins, just make sure that the install function in this file installs the plugin instead, as well as exports the plugin directly for those who are not using it via script tag (webpack, etc.). There are probably some finer implementation details outside this simple explanation, but nothing that would be a huge reach.

**Comment by ShailenNaidoo** [comment]
@mgdodge Thanks :) Tried it out and it is working nicely
