### ISSUE TITLE
Inconsistent output between `npm publish` and `yarn publish` causing unwanted files to leak when publishing to npm

### ISSUE THREAD

**Issue by fuxingloh** [team-innovation/vue-sfc-rollup#40]
```json
"files": [
  "dist/*",
  "src/**/*.vue",
  "!src/serve-dev.*"
],
```

This effects yarn only, when running `yarn pack`, the field `"files"` specified in `package.json` used for whitelisting is entirely ignored because of `"!src/serve-dev.*"`. The think the implementation in yarn is stateless meaning it will take the glob pattern of all 3 output. This results in my entire directly being published to npm when I use `yarn publish` which can leak unwanted secrets.

References:
https://classic.yarnpkg.com/en/docs/package-json/#toc-files
https://docs.npmjs.com/files/package.json#files

For my project, I removed "files" and used `.npmignore` instead as they both produce the same result. https://github.com/fuxingloh/vue-horizontal-list/commit/252f98821eacfbb7aa3de51bb56d2106fbfd9361

### NPM: `npm pack` < 👍
Version: 6.14.4
`npm pack && tar -xvzf *.tgz && rm -rf package *.tgz`

#### Output:
```
x package/LICENSE
x package/dist/vue-horizontal-list.esm.js
x package/dist/vue-horizontal-list.min.js
x package/dist/vue-horizontal-list.ssr.js
x package/package.json
x package/README.md
x package/src/vue-horizontal-list.vue
```

### YARN: `yarn pack` < 👎
Version: 1.22.4
`yarn pack && tar -xvzf *.tgz && rm -rf package *.tgz`

#### Output:
```
x package
x package/.DS_Store
x package/.browserslistrc
x package/.gitignore
x package/.idea
x package/.npmignore-t
x package/LICENSE
x package/README.md
x package/babel.config.js
x package/build
x package/demo.png
x package/dist
[...]
```

**Comment by mgdodge** [comment]
There is an open bug with yarn surrounding the differences between npm and yarn in this regard. According to [this comment](https://github.com/yarnpkg/yarn/issues/685#issuecomment-457618561) on the thread, the comment immediately following, and [the relevant article](https://medium.com/@jdxcode/for-the-love-of-god-dont-use-npmignore-f93c08909d8d), it would seem that using `.npmignore` is opting for a blacklist approach instead of a whitelist. While this may work for some, it comes with more inherent risks - thus I am opting against it.

With a little tweak, I can remove the need for the negate flag entirely, and thus make the files array work for both yarn and npm. I will look into getting this done in the next patch release, which is already well under way.

**Comment by mgdodge** [comment]
FYI, v3.0.0 just released, addresses this
