### ISSUE TITLE
vue-sfc-rollup for vuetify based components

### ISSUE THREAD

**Issue by dsvanidze** [team-innovation/vue-sfc-rollup#44]
Hi @mgdodge,

thank you very much for this great tool! I have Vuetify based components, but when I build an `.esm` bundle and import components in other project with `npm link`, vuetify components do not load. 

I forked your repository and created an example of my problem [https://github.com/dsvanidze/vue-sfc-rollup/tree/master/examples/sfc-rollup-vuetify](https://github.com/dsvanidze/vue-sfc-rollup/tree/master/examples/sfc-rollup-vuetify).

I would like to import the component in other project as I do [here](https://github.com/dsvanidze/vue-sfc-rollup/blob/master/examples/sfc-rollup-vuetify/dev/serve.vue). So, I can use it like `<sfc-rollup-vuetify-sample v-model="text" />`in another project.

When I import it in another project, I get many errors caused by Vuetify in the browser (Chrome).

1. `Unknown custom element: <v-row> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`
1. `Unknown custom element: <v-col> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`
1. `Unknown custom element: <v-textarea> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`
...and so on.

What can I change that my components work appropriately in other projects? I tested the behaviour in Vue and Nuxt project with installed Vuetify, but same errors occur. 

Thanks in advance,
Davit

**Comment by mgdodge** [comment]
This is not a problem with vue-sfc-rollup, but with the way vuetify is used. I found [this github issue](https://github.com/vuetifyjs/vuetify-loader/issues/70#issuecomment-562007860) from vuetify-loader helpful.

The short of it is that vuetify-loader (used by webpack, and thus vue-cli and probably nuxt projects) is used for tree-shaking, and it automatically detects which vuetify components are used in your app, eliminating the rest. It can't detect which vuetify components are used by third party libraries unless each library component specifically imports the pieces of vuetify it uses. Also, `vuetify/lib` should be listed in the rollup externals config. Then it should work for esm instances.

I can't say for sure that would work with ssr/iife usage, however. That might require some more customization to the rollup config for those builds.

Since all of this is very library-specific stuff, I am closing this issue. The discussion belongs in the vuetify or vuetify-loader projects, more specifically the issue I linked to above.
