### ISSUE TITLE
Looks very complicated

### ISSUE THREAD

**Issue by fairking** [team-innovation/vue-sfc-rollup#53]
Looks very complicated to me. I don't think people are going to use it?

Is there any way just to have those components in some share folder? Eg.:
```
Solution
|--Project One
    |--dist
    |--src
        |--App.vue
        |--main.ts
    |--package.json
|--Project Two
    |--dist
    |--src
        |--App.vue
        |--main.ts
    |--package.json
|--Shared
    |--src
        |--Component 1
        |--Component 2
    |--package.json
```

Is it possible to use symlink in this case? Eg.:
```
Solution
|--Project One
    |--dist
    |--src
        |--Components (symlink to ../../Shared/src/)
        |--App.vue
        |--main.ts
    |--package.json
|--Project Two
    |--dist
    |--src
        |--Components (symlink to ../../Shared/src/)
        |--App.vue
        |--main.ts
    |--package.json
|--Shared
    |--src
        |--Component 1
        |--Component 2
```

Otherwise just copy files on build by script or using webpack (something like [copy-webpack-plugin](https://webpack.js.org/plugins/copy-webpack-plugin/)).

**Comment by mgdodge** [comment]
I don't quite understand what you are getting at here. This repo, by itself, might be a little complicated, but the output it creates is very minimal, very similar to what your sample "Shared" folder produces.

Also, this utility is intended to create vue components to share via npm, so symlink is not required - those projects consume the components via npm. If you absolutely need to consume via symlink, perhaps running [npm link](https://docs.npmjs.com/cli/link) will set them up the way you need, so that you "install" via npm like your users will, but on local development you can use the symlink.

Closing this issue, as it seems a matter of opinion, not an actual bug/issue.

**Comment by fairking** [comment]
Thanks for the response. It was just my opinion. Thought there are better solutions around.
