### ISSUE TITLE
Importing one component in library mode imports all

### ISSUE THREAD

**Issue by lewishowles** [team-innovation/vue-sfc-rollup#55]
Thanks for the tool, it really helped me get up and running with our component library for Vue 3!

I'm not sure if this is something to do with how the library is generated, or how Vite is building the final app, but I'm using `4.0.0-beta.0` for a Vue 3 library used in a Vue 3 project, which is built with Vite, and I noticed that tree shaking for the output library doesn't seem to work. I saw #39 but I'm not sure if that's the same issue. 

I'm importing the `esm` version, and we have around 91 helper components. It seems like importing one or more of the components into the app - e.g. `import { SimpleDonut } from '@software2-libraries/ui-components';` takes the built file from 50k to 500k, and it doesn't matter how many components I try to import.

**Comment by mgdodge** [comment]
Logged [this bug](https://github.com/vuejs/rollup-plugin-vue/issues/401) today with rollup-plugin-vue, which addresses tree-shaking. The bug you referred to was for vue2, and had been resolved. It seemed to crop up again recently, due partially to upstream changes.

Just released v4.0.0-beta.1 which in my latest tests is very tree-shakeable for vue2, but not vue3 at all. The bug I logged illustrates that the tree-shaking issues are not due to this utility, since all it does is scaffold the config - the actual output is from rollup-plugin-vue.

The bug includes a sample repo showing the exact same code/config creating vastly different tree-shakability results between vue2 and vue3. You'll probably want to keep an eye on that bug report - when it gets resolved, there should be no need to change this utility unless rollup-plugin-vue gets a semver-major update as part of the fix.

**Comment by lewishowles** [comment]
Great, thanks for taking a look!

**Comment by mgdodge** [comment]
Updated [my bug report](https://github.com/vuejs/rollup-plugin-vue/issues/401) just the other day with addl. research regarding tree-shaking in Vue 3 version. Still an upstream problem, but at least there is more info an a very manual workaround.

**Comment by chenkai0520** [comment]
Same error for me, this question has been around for some time，tree-shaking can work normally in vite, but not in vue-cli

**Comment by mgdodge** [comment]
The decision has been made to deprecate `vue-sfc-rollup` in favor of better tooling in the Vue ecosyste, specifically the [vite "library build"](https://vitejs.dev/guide/build.html#library-mode) configuration. It is an excellent project, which is capable of everything vue-sfc-rollup strived to accomplish, and more.
