### ISSUE TITLE
Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by VictorLessa** [team-innovation/vue-sfc-rollup#58]
When I create a component for example and compile it
When using it, the following error appears: Failed to mount component: template or render function not defined.

**Comment by mgdodge** [comment]
Please provide a sample repo to investigate this further.

**Comment by tuantiensiu** [comment]
Hello, I want to build my component library. But I can't npm run build or import component in out project. You can see more problem in my link: https://docs.google.com/document/d/186O0iANAbYfNOgoBQNX-wDGn9f-lAHdKtrsLzy5io88/edit?usp=sharing

**Comment by mgdodge** [comment]
A google doc is not a sample repo. Without access to code, it's impossible to identify exactly what is going on.

In the google doc screenshots, I was able to tell that `import TienButton from 'tien-library';` would fail, since that would not import a single component, but the entire library. To use the entire library, you would call `Vue.use` (vue2) or `app.use` (vue 3) with that import. If you really want a single component, that should be rewritten as  `import { TienButton } from 'tien-library';` (note curly braces) with the rest of your code as-is.

That example alone indicates to me that there is probably other incorrect code that you have written, and no real problem with vue-sfc-rollup. I am closing this as a false bug report unless you are able to provide actual code to look further into things.
