### ISSUE TITLE
Consider creating a Vue CLI v3 plugin for this repo

### ISSUE THREAD

**Issue by kemalcany** [team-innovation/vue-sfc-rollup#6]
Hello!

Very useful repo, thank you very much for this!
(Also the short recipe [here](https://vuejs.org/v2/cookbook/packaging-sfc-for-npm.html) )

One short question tough:

Have you considered wrapping this repo in a Vue CLI plugin so the contents of this repo can be discovered and used with the new Vue CLI (also the UI)? Or do you think there is no value doing it since this repo is already designed to do scaffolding (ie template generation etc.) 

Thank you!!

**Comment by mgdodge** [comment]
Interesting idea. I could see benefit in having the cli scaffold something similar to this, but due to some of the differences between the two, I am not sure just 'wrapping' this repo as a plugin is feasible.

When this repo was created, the cli didn't yet have the ability to create an npm-specific build. [It now does](https://cli.vuejs.org/guide/build-targets.html#library), though a little different in its execution. The cli uses webpack behind the scenes (main reason I don't see this repo being 'wrapped' as a plugin,) does not scaffold the package.json properly for you, and does not generate an esm version of the component.

Good idea, though, and definitely worth suggesting some feature enhancements for the cli (esm output, package.json tweaks.)

Thanks for the feedback!
