### ISSUE TITLE
Error with dev server (using TypeScript & Vue 3)

### ISSUE THREAD

**Issue by Uninen** [team-innovation/vue-sfc-rollup#62]
First, Thank You for this project 👍 

I Installed the latest beta of `vue-sfc-rollup` and created a test project with Vue 3 + TypeScript. Did not change any file or do any modifications after the creation process. The project builds but the dev server won't restart. I'm assuming the babel config is wrong, but couldn't come up with any working solution after a couple of hours of testing out various configs.

The error message location depends a little bit on the babel config, currently I get this:

```
 error  in ./src/lib-components/testproject-sample.vue?vue&type=script&lang=ts

Module parse failed: Unexpected token (22:24)
File was processed with these loaders:
 * ./node_modules/cache-loader/dist/cjs.js
 * ./node_modules/babel-loader/lib/index.js
 * ./node_modules/ts-loader/index.js
 * ./node_modules/cache-loader/dist/cjs.js
 * ./node_modules/vue-loader-v16/dist/index.js
You may need an additional loader to handle the result of these loaders.
|       } = this;
|       if (!message.action) return 'initialized';
>       return `${message?.action} ${message.amount ?? ''}`.trim();
|     }
| 

 @ ./src/lib-components/testproject-sample.vue?vue&type=script&lang=ts 1:0-338 1:0-338 1:339-666 1:339-666
 @ ./src/lib-components/testproject-sample.vue
 @ ./src/lib-components/index.ts
 @ ./src/entry.esm.ts
 @ ./dev/serve.ts
 @ multi (webpack)-dev-server/client?http://192.168.1.61:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./dev/serve.ts
```

Maybe `vue-loader-v16` changed something or there was some other regression after [this change](https://github.com/team-innovation/vue-sfc-rollup/commit/f2db4c583c051add4290b7e4eb1fa4f7e15326cf)?

**Comment by Uninen** [comment]
I just found the culprit after creating a new repo for repro. I didn't change any code but did change the deps, it seems. Everything works with Rollup v 0.30 up to version 0.33 but if you upgrade rollup to 0.34 you get the error message above (updated the message from a fresh install).

Couldn't see anything obvious what would brake here but as I can now easily work around this, not so big issue for me anymore.

Again, thanks for the project 🙏

**Comment by Uninen** [comment]
Duh. Updated `rollup-plugin-vue` from beta 10 to beta 11 and now everything works with the latest packages. Sorry for the noise.

**Comment by fredrivett** [comment]
I ran into a very similar error message here, focussed around the same line:

```
 ERROR  Failed to compile with 1 error                                                                                                                                                                                                                                                                                                                              17:48:51

 error  in .[redacted]/dist/component-library.esm.js

Module parse failed: Unexpected token (22:24)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|       } = this;
|       if (!message.action) return "initialized";
>       return `${message?.action} ${message.amount ?? ""}`.trim();
|     }
|

 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Home.vue?vue&type=script&lang=js& 11:0-64 16:28-50
 @ ./src/views/Home.vue?vue&type=script&lang=js&
 @ ./src/views/Home.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.0.4:8999&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
 ```
 
 This was with no changes made at all to a freshly installed project via the `vue-sfc-rollup` prompts. I was using the latest `vue-sfc-rollup` @ `v4.0.0`, though I also tried out using an old version 6 months prior in my hunt to find out what the problem was, so I don't think this issue is introduced recently.
 
The issue arose not when viewing the component with `yarn run serve` inside this project, but when importing it via an NPM install into another. In that other project is where I got the error above.

It turns out that simply changing the offending line (24) to something like `return "5"` got rid of the error entirely.

That helped me track it down, the offending part was down to two parts in that line.

### 1: `message?.action`

By default a project installed via `vue-cli` choosing vue 2 as the version does not come with support for optional chaining, so this blows up when seeing `?.` here.

### 2: `message.amount ?? ""`

The same is true for nullish coalescing.

Removing these two parts stopped things from blowing up.

I imagine this is a common setup (a plain, `vue-cli` generated project) with the base setup from `vue-sfc-rollup` importing the test component to try it out before adding custom ones, so I think it makes sense to remove the dependency on the requiring project to support optional chaining and nullish coalescing for the example to work.

I've created a PR with a fix for this that should stop others running into this issue and seems to have no downside that I can see: https://github.com/team-innovation/vue-sfc-rollup/pull/71

**Comment by webistomin** [comment]
I had the same error. I changed the target property to `ES2019` in `tsconfig.json`.
