### ISSUE TITLE
Unknown plugin transform-object-rest-spread

### ISSUE THREAD

**Issue by WhitePolice** [team-innovation/vue-sfc-rollup#7]
I'm using Spread Syntax and getting `Unknown plugin transform-object-rest-spread` error when compiling.

**Comment by mgdodge** [comment]
To be sure I understand, are you getting this when running sfc-rollup-init, or after, when you are compiling the component? A few things to try:

- The template used to generate the rollup config likely doesn't contain the latest versions of the npm dependencies, try updatint them
- The template uses rollup-plugin-buble, which says it has support for object rest spread. You could try switching it out for [rollup-plugin-babel](https://github.com/rollup/rollup-plugin-babel). Babel is more widely used for transpiling, but does require more configuration and can add code bloat.

A small example would also be helpful if the above don't get you any closer to a resolution.

**Comment by WhitePolice** [comment]
BTW, before that I also encounter `(buble plugin) CompileError: Object spread operator requires specified objectAssign option with 'Object.assign' or polyfill helper.` error. I just add { objectAssign: 'Object.assign' } fixed the issue.

**Comment by mgdodge** [comment]
The problem seems to be with the specific configuration of buble, then. That is something that is outside the scope of this utility. Closing this issue, refer to [this example](https://github.com/vuejs/vue-hackernews-2.0/issues/87) for how others have resolved similar issues. Or feel free to use [rollup-plugin-babel](https://github.com/rollup/rollup-plugin-babel) instead.
