### ISSUE TITLE
why is script block ahead of template and style

### ISSUE THREAD

**Issue by laoshaw** [team-innovation/vue-sfc-rollup#78]
nearly all SFC I saw with Vue has the consistent order: template --> script --> style, why vue-sfc-rollup rolls its own order and put script first? I know it's not something critical but consistency actually matters.

**Comment by mgdodge** [comment]
In the first VueConf US meetup, one of the courses there mentioned this as a best practice. The [sample repo](https://github.com/bencodezen/vue-enterprise-boilerplate) shared in that class, which is still used/updated, does components this way. Even the [official style guide](https://vuejs.org/v2/style-guide/#Single-file-component-top-level-element-order-recommended) examples list it first in their list of "good" code styles.

The reasoning is that when a component has a bug, typically it is the script that needs to be worked on, not the template markup or styles. So putting the tags in this order means most of the time, you won't need to scroll as far when you do need to work in the code.

Closing this as a non-issue, since it is a) not broken, just coding style, and b) follows some best practices used elsewhere.
