### ISSUE TITLE
css lost in vue3-typescript

### ISSUE THREAD

**Issue by aardpro** [team-innovation/vue-sfc-rollup#83]
Hi!

I use sfc-init build vue2 and javascript sfc and it's perfect,thank you!

But with vue3 and typescript sfc, the css block in <style scope></style> is ignored.

Can you resolve this?

**Comment by mgdodge** [comment]
Which version are you using? I noticed this bug recently while researching another one, and it is fixed in the most recent version. v4.0.4 - if you aren't using the scaffolding produced by that one, give it a try.

The bug that was being researched was #80, and there are two comments which indicate how to fix the issue, [this one](https://github.com/team-innovation/vue-sfc-rollup/issues/80#issuecomment-801945870) and [another one](https://github.com/team-innovation/vue-sfc-rollup/issues/80#issuecomment-803469689) just a little farther down in the thread.

If neither the latest version or the comments help, please provide a sample repo to reproduce. If they do, feel free to close this bug.

**Comment by aardpro** [comment]
I installed 4.0.4 rollup.config.js and fixed the problem ,thank you!
