### ISSUE TITLE
Cypress I can't load it properly

### ISSUE THREAD

**Issue by GoldraK** [team-innovation/vue-sfc-rollup#90]
Hello,
thank you first for the package.

I want to test the package with Cypress but I can't get it to start correctly.

Install the `@vue/cli-plugin-e2e-cypress`  package 

And when executing

`npm run test: e2e`

I get the following error

```
  ERROR Failed to compile with 1 error 20:31:50

This relative module was not found:

* ./src/main.js in multi ./src/main.js
```

So I create the file `vue.config.js` with the following configuration

```
module.exports = {
     pages: {
         app: {
             entry: 'dev / serve.js',
         },
     },
};
```

I start it again and it performs the build but now when accessing I receive

`Cannot GET /`

I don't know that I'm doing the truth wrong.

Thanks for your time and help.

**Comment by mgdodge** [comment]
In a fresh project, I was able to get it to work just fine. Slightly different process, but you're pretty close:

After scaffolding, I ran:
```bash
vue add e2e-cypress
```
and that added the plugin with all the wiring that the vue cli needs.

Then, I added a very similar vue.config.js to what you have here:
```js
module.exports = {
     pages: {
         index: {
             entry: 'dev/serve.js',
         },
     },
};
```

The difference is because the sample test generated by the cypress install looks for the root url - `index` instead of `app`.

Starting things up after that, cypress ran everything just fine. The test out of the box fails, because it's looking for the boilerplate markup from the cli. But editing the test to look for the scaffolded component was trivial.

Closing this issue since nothing is wrong with the scaffolded code, it was all custom configuration.
