### ISSUE TITLE
Feature: Vue+SCSS option(while generating a project with CLI).

### ISSUE THREAD

**Issue by otabekoff** [team-innovation/vue-sfc-rollup#98]
Hello!
My name is Otabek. I am happy to write something here.

Could you add feature of generating Vue+SCSS template?
When we tried default template, we 95% of developers are being unable to get what we want!
You know preprocessor is a great tool while creating a new component library.
So, I am going to ask you to add this feature in the coming versions.

Thank you!
With warm regards Otabek Mirzo.

**Comment by mgdodge** [comment]
As indicated in the description of this package, "It doesn't assume any particular flavor of CSS". Preprocessors are definitely helpful, but forcing one on someone is not in line with the "minimalist" approach vue-sfc-rollup is taking. There are numerous developers who don't write SCSS - some prefer LESS, Stylus, or even pure CSS.

Also, adding support for SCSS is trivial - the code created by this scaffolding is ready for development via vue-cli, and the vue cli has support built-in. All you need to do is install the appropriate node modules and change the `<style>` tags to `<style lang="scss">` as per [the official documentation](https://cli.vuejs.org/guide/css.html). Compiling works just fine as well, with no modifications necessary if you plan on letting vue inline the styles into the JS. Extracting the CSS into external files would require extra setup no matter which flavor of CSS you use, so that's beyond the scope of what you're asking here.

Closing this issue as it is not in line with the purpose of this utility.
